apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-service
spec:
  type: NodePort   # <-- ici au lieu de ClusterIP
  selector:
    app: {{ .Release.Name }}-django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # <-- tu choisis un port entre 30000-32767
